# Generated by Django 3.1.5 on 2021-02-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pyb_date',
            new_name='pub_date',
        ),
    ]
